#include: package:lint/analysis_options_package.yaml

analyzer:
  strong-mode:
    implicit-dynamic: false
  exclude:
    - example/**
    - test/**
    - build/**
    - android/**
    - ios/**
  errors:
    non_nullable_equals_parameter: ignore
    unreachable_switch_default: ignore
    invalid_null_aware_operator: ignore
    deprecated_member_use: ignore

linter:
  rules:
    close_sinks: true
    sort_constructors_first: false
    avoid_classes_with_only_static_members: false
    avoid_void_async: false
    avoid_positional_boolean_parameters: false
    avoid_function_literals_in_foreach_calls: false
    prefer_constructors_over_static_methods: false
    sort_unnamed_constructors_first: false
    sized_box_for_whitespace: false
    sort_pub_dependencies: false
    avoid_unnecessary_containers: false
    use_setters_to_change_properties: false

